#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
cp ${OPENSHIFT_REPO_DIR}tests/data/metadata_good/baz.json ${OPENSHIFT_DATA_DIR}repodata-new.json
echo "Copied the metada"
